apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: s3proxy-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: default-irsa
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: s3proxy-ingress-auth-hashed
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: s3proxy-secrets
    kind: ParameterStore
  target:
    name: s3proxy-ingress-auth-hashed
    creationPolicy: Owner
  data:
    - secretKey: s3proxy
      remoteRef:
        key: /devnet/admin/S3PROXY_INGRESS_AUTH

