---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-udp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 32526
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  # loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: wireguard
    port: 51820
    targetPort: 51820
    nodePort: 30820
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-tcp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32526
    targetPort: 80
    protocol: TCP

