apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: grafana-secrets
    kind: ParameterStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /testnet/admin/GRAFANA_ADMIN_PASSWD
    - secretKey: admin-user
      remoteRef:
        key: /testnet/admin/GRAFANA_ADMIN_USER
