apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-fluentbit
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: testnet-nezha
  project: default
  source:
    chart: fluent-bit
    helm:
      values: |
        image:
          repository: cr.fluentbit.io/fluent/fluent-bit
          # Overrides the image tag whose default is {{ .Chart.AppVersion }}
          tag: "1.9.5"
          pullPolicy: Always

        nameOverride: "fluentbit"

        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::440257901289:role/testnet-nezha-fluentbit"
          name: fluentbit

        tolerations:
          - effect: "NoSchedule"
            operator: "Exists"

        ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level {{ .Values.logLevel }}
                Parsers_File parsers.conf
                Parsers_File custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On

          ## https://docs.fluentbit.io/manual/pipeline/inputs
          inputs: |
            [INPUT]
                Name              tail
                Tag               kube.*
                Parser            docker
                Path              /var/log/containers/*.log
                DB                /var/log/flb_kube.db
                Mem_Buf_Limit     5MB
                Refresh_Interval  10
                Ignore_Older      1m
                Buffer_Max_Size   10MB
                Skip_Long_Lines   On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Systemd_Filter _SYSTEMD_UNIT=docker.service
                Read_From_Tail On

          ## https://docs.fluentbit.io/manual/pipeline/filters
          filters: |
            [FILTER]
                Name             kubernetes
                Match            kube.*
                Kube_URL         https://kubernetes.default.svc:443
                Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix  kube.var.log.containers.
                Merge_Log        On
                Merge_Log_Key    log_processed
                Keep_Log         Off
                Annotations      Off
                Labels           Off
                # K8S-Logging.Parser On
                # K8S-Logging.Exclude On
                # Use_Kubelet On

            [FILTER]
                Name          rewrite_tag
                Match         kube.*
                #Rule          $log_processed['source'] ^(apache)$  apache.$TAG false
                # Rule          $kubernetes['namespace_name'] ^(runners)$ runners.$TAG false
                # Rule          $kubernetes['namespace_name'] ^(argocd)$ argocd.$TAG false
                # Rule          $kubernetes['namespace_name'] ^(kube-system)$ kube-system.$TAG false

                Rule          $kubernetes['container_name'] ^(nezha-api)$ nezha-api.$TAG false
                Rule          $kubernetes['container_name'] ^(nezha-platform)$ nezha-platform.$TAG false
                Rule          $kubernetes['container_name'] ^(indexer-deposits)$ indexer-deposits.$TAG false
                Rule          $kubernetes['container_name'] ^(indexer-epochs)$ indexer-epochs.$TAG false
                Rule          $kubernetes['container_name'] ^(lottery)$ lottery.$TAG false
                Emitter_Name  re_emitted

            # [FILTER]
            #     Name grep
            #     Match atlas.*
            #     Exclude $agent (kube-probe|ELB-HealthChecker)

            # [FILTER]
            #     Name record_modifier
            #     Match *
            #     Remove_key log_cluster
            #     Remove_key kubernetes.docker_id
            #     Remove_key kubernetes.pod_id
            #     Remove_key kubernetes.container_hash

          ## https://docs.fluentbit.io/manual/pipeline/outputs
          outputs: |
            [OUTPUT]
                Name cloudwatch_logs
                Match lottery.*
                region eu-west-1
                log_group_name testnet-eks
                log_stream_name lottery
                log_retention_days 7
                auto_create_group On

            [OUTPUT]
                Name cloudwatch_logs
                Match indexer-deposits.*
                region eu-west-1
                log_group_name testnet-eks
                log_stream_name indexer-deposits
                log_retention_days 7
                auto_create_group On

            [OUTPUT]
                Name cloudwatch_logs
                Match indexer-epochs.*
                region eu-west-1
                log_group_name testnet-eks
                log_stream_name indexer-epochs
                log_retention_days 7
                auto_create_group On

            [OUTPUT]
                Name cloudwatch_logs
                Match nezha-api.*
                region eu-west-1
                log_group_name testnet-eks
                log_stream_name nezha-api
                log_retention_days 7
                auto_create_group On

            [OUTPUT]
                Name cloudwatch_logs
                Match nezha-platform.*
                region eu-west-1
                log_group_name testnet-eks
                log_stream_name nezha-platform
                log_retention_days 7
                auto_create_group On

            # [OUTPUT]
            #     Name cloudwatch_logs
            #     Match kube-system.*
            #     region eu-west-1
            #     log_group_name testnet-eks
            #     log_stream_name kube-system-namespace
            #     log_retention_days 7
            #     auto_create_group On

            # [OUTPUT]
            #     Name cloudwatch_logs
            #     Match argocd.*
            #     region eu-west-1
            #     log_group_name testnet-eks
            #     log_stream_name argocd-namespace
            #     log_retention_days 7
            #     auto_create_group On

            # [OUTPUT]
            #     Name cloudwatch_logs
            #     Match runners.*
            #     region eu-west-1
            #     log_group_name testnet-eks
            #     log_stream_name runners-namespace
            #     log_retention_days 7
            #     auto_create_group On

            # [OUTPUT]
            #     Name cloudwatch_logs
            #     Match   *
            #     region eu-west-1
            #     log_group_name testnet-eks
            #     log_stream_prefix testnet-fluentbit-
            #     log_retention_days 7
            #     auto_create_group On

          ## https://docs.fluentbit.io/manual/pipeline/parsers
          customParsers: |
            # [PARSER]
            #     Name docker_no_time
            #     Format json
            #     Time_Keep Off
            #     Time_Key time
            #     Time_Format %Y-%m-%dT%H:%M:%S.%L

            # [PARSER]
            #     Name   json
            #     Format json
            #     Time_Key time
            #     Time_Format %d/%b/%Y:%H:%M:%S %z

            [PARSER]
                Name        docker
                Format      json
                Time_Key    time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                Time_Keep   On
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.20.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
