apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: github-runners-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: devnet-github-runners
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-runners-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: github-runners-secrets
    kind: ParameterStore
  target:
    name: github-runners-secrets
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: /devnet/runners/GITHUB_TOKEN
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: bitbucket-runners-artkai-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: github-runners-secrets
    kind: ParameterStore
  target:
    name: bitbucket-runners-artkai-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /devnet/runners/ARTKAI_PLATFORM_OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /devnet/runners/ARTKAI_PLATFORM_OAUTH_CLIENT_SECRET
    - secretKey: ACCOUNT_UUID
      remoteRef:
        key: /devnet/runners/ARTKAI_PLATFORM_ACCOUNT_UUID
    - secretKey: RUNNER_UUID
      remoteRef:
        key: /devnet/runners/ARTKAI_PLATFORM_RUNNER_UUID
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: artkai-api-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: github-runners-secrets
    kind: ParameterStore
  target:
    name: artkai-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /devnet/runners/ARTKAI_API_OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /devnet/runners/ARTKAI_API_OAUTH_CLIENT_SECRET
    - secretKey: ACCOUNT_UUID
      remoteRef:
        key: /devnet/runners/ARTKAI_API_ACCOUNT_UUID
    - secretKey: RUNNER_UUID
      remoteRef:
        key: /devnet/runners/ARTKAI_API_RUNNER_UUID
