apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: lottery-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: default-irsa
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: lottery-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: lottery-secrets
    kind: ParameterStore
  target:
    name: lottery-backends-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /devnet/lottery/DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: /devnet/lottery/DB_USER
    - secretKey: DB_HOST
      remoteRef:
        key: /devnet/nezha/DB_POSTGRES_HOST # shared namespace
    - secretKey: DB_NAME
      remoteRef:
        key: /devnet/lottery/DB_NAME
    - secretKey: SOLANA_ADMIN_KEYPAIR
      remoteRef:
        key: /devnet/lottery/SOLANA_ADMIN_KEYPAIR
    - secretKey: SOLANA_INVESTOR_KEYPAIR
      remoteRef:
        key: /devnet/lottery/SOLANA_INVESTOR_KEYPAIR

