apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-namespacelimits
  namespace: argocd
  labels:
    environment: development
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/namespacelimits/development
    repoURL: git@github.com:mlabs-haskell/nezha.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
