apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainnet-external-dns
  namespace: argocd
spec:
  destination:
    name: mainnet
    namespace: external-dns
  project: default
  source:
    chart: external-dns
    helm:
      values: |-
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::367391507260:role/mainnet-nezha-external-dns
        domainFilters:
          - nezha.fi
          - internal.service
        txtOwnerId: mainnet.nezha.fi
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

