apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainnet-external-secrets
  namespace: argocd
spec:
  destination:
    name: mainnet
    namespace: external-secrets
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

