kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artkai
  namespace: artkai
rules:
- apiGroups: ["extensions", "apps", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["*"]
