apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: indexer-epochs-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: default-irsa
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: indexer-epochs-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: indexer-epochs-secrets
    kind: ParameterStore
  target:
    name: indexer-epochs-secrets
    creationPolicy: Owner
  data:
    - secretKey: INDEXER_DB_PASSWORD
      remoteRef:
        key: /mainnet/indexer/DB_PASSWORD
    - secretKey: INDEXER_DB_USER
      remoteRef:
        key: /mainnet/indexer/DB_USER
    - secretKey: INDEXER_DB_NAME
      remoteRef:
        key: /mainnet/indexer/DB_NAME
    - secretKey: INDEXER_DB_HOST
      remoteRef:
        key: /mainnet/nezha/DB_POSTGRES_HOST # shared namespace
    - secretKey: SOLANA_ADMIN_KEYPAIR
      remoteRef:
        key: /mainnet/indexer/SOLANA_ADMIN_KEYPAIR
    - secretKey: SOLANA_INVESTOR_KEYPAIR
      remoteRef:
        key: /mainnet/indexer/SOLANA_INVESTOR_KEYPAIR
    - secretKey: ARTKAI_WEBHOOK_TOKEN
      remoteRef:
        key: /mainnet/indexer/ARTKAI_WEBHOOK_TOKEN

