apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: grafana-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: grafana
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: grafana-secrets
    kind: ParameterStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /development/admin/GRAFANA_ADMIN_PASSWD
    - secretKey: admin-user
      remoteRef:
        key: /development/admin/GRAFANA_ADMIN_USER
