apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notifications-nginx-ingress-controller
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: prometheus
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-nginx-ingress-controller-nginx-ingress
