[features]
seeds = false
skip-lint = false
[programs.localnet]
staking = "2beVdAd5fpgyxwspZBfJGaqTLe2sZBm1KkBxiZFc1Mjr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "validator/setup/keys/admin.json"

[workspace]
members = ["workspace/program/staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
